server:
  port: 8081

spring:
  application:
    name: moviedb_helper

  datasource:
    url: ${datasourceUrl}
    username: ${dbUsername}
    password: ${dbPassword}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: false

logging:
  level:
    it.lraffaele.themoviedbhelper: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework: info

